apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc_deploy
  template:
    metadata:
      labels:
        app: abc_deploy
    spec:
      containers:
        - name: abc-app
          image: amarjeetkaur111/igp-cicd:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
